cargo-features = ["edition2021"]

[package]
name = "wasm-utils"
description = "WASM Utilities from Webb"
version = "0.1.1"
authors = ["Webb Developers"]
categories = ["wasm", "cryptography", "arkworks"]
readme = "README.md"
edition = "2021"
homepage="https://webb.tools"
repository = "https://github.com/webb-tools/webb.js/tree/master/packages/wasm-utils"
documentation = "https://docs.rs/wasm-utils"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib" , "rlib"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true

[dependencies]
ark-ff = { version = "^0.3.0", default-features = true }
ark-serialize = "0.3.0"
ark-crypto-primitives = { version = "^0.3.0", default-features = true, features = ["r1cs"] }
ark-ed-on-bn254 = { version = "^0.3.0", default-features = true, features = ["r1cs"] }
ark-bn254 = { version = "^0.3.0", default-features = true, features = ["curve"] }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = ["curve"] }
webb-pedersen-hash = { version = "0.1.0", git = "https://github.com/webb-tools/webb-rs.git" }
# arkworks-gadgets = { version = "0.4.19", default-features = true }
# arkworks-circuits = { version = "0.4.19", default-features = false }
# arkworks-utils = { version = "0.4.19", default-features = false }
arkworks-gadgets = { path = "../../../arkworks-gadgets/arkworks-gadgets" }
arkworks-circuits = { path = "../../../arkworks-gadgets/arkworks-circuits" }
arkworks-utils = { path = "../../../arkworks-gadgets/arkworks-utils" }

wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
rand = { version = "0.8.3", features = ["getrandom"] }
getrandom = { version = "0.2.3", features = ["js"] }
hex = "0.4"
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure.
console_error_panic_hook = "0.1.5"
# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. However, it is slower than the default
# allocator, so it's not enabled by default.
wee_alloc = { version = "0.4.2", optional = true }
rayon = { version = "1.5", optional = true }
wasm-bindgen-rayon = { version = "1.0", optional = true }

# The `web-sys` crate allows you to interact with the various browser APIs,
# like the DOM.
[dependencies.web-sys]
version = "0.3.22"
features = ["console"]

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.3"
js-sys = "0.3"
lazy_static = "1.4"

[features]
# If you uncomment this line, it will enable `wee_alloc`:
#default = ["wee_alloc"]
parallel = [
  "rayon",
  "wasm-bindgen-rayon",
  "arkworks-gadgets/parallel",
  "arkworks-circuits/parallel",
  "arkworks-utils/parallel",
  "ark-ff/parallel",
]
